# Define the final output of the workflow
rule all:
    input:
        vcf = "results/44/mapping/v21/NGSEP/vcf/44_merged.vcf.gz",
        DB = expand("results/44/mapping/v21/GATK/DB/{chrom}/DB_{chrom}", chrom=['Chr01','Chr02','Chr03','Chr04','Chr05','Chr06','Chr07','Chr08','Chr09','Chr10','Chr11'])

# Include modular rules for different stages of the workflow
include: "rules/common.smk"
include: "rules/ref.smk"
include: "rules/demultiplexing.smk"
include: "rules/read_trimming.smk"
include: "rules/mapping.smk"
include: "rules/variant_calling_NGSEP.smk"
include: "rules/variant_calling_GATK.smk"
