include: "rules/common.smk"

rule all:
    input:
        vcf = expand("{basedir}/results/{plate}/mapping/bwa/{ref}/stats/{plate}_merged_Q{qual}_Dp{dp}_MAF{maf}_stats_plot.pdf",
        basedir = basedir,
         plate = [46,47,48,49,50],
          ref="UI111",
          qual = "40",
          dp = "5",
          maf = "0.05"),

# Modules
include: "rules/ref.smk"
include: "rules/demultiplexing.smk"
include: "rules/read_trimming.smk"
include: "rules/mapping.smk"
include: "rules/variant_calling_NGSEP.smk"
include: "rules/variant_calling_GATK.smk"
include: "rules/quality_check.smk"
include: "rules/filter.smk"