sequencing_units: config/sequencing_units.tsv
sample_units: config/samples.tsv
references: config/references.tsv

resources_config: config/resources.yaml

demultiplexing:
  re_enzyme: "apeKI"

bigtmp: tmpdir/

trimmomatic:
    pe:
      trimmer:
        - "LEADING:5"
        - "TRAILING:5"
        - "SLIDINGWINDOW:4:5"
        - "MINLEN:36"
        - "ILLUMINACLIP:data/adapter.fa:2:20:7:2"

NGSEP:
    path: /home/scruz/software//NGSEPcore/NGSEPcore_5.0.0.jar
    SingleSampleVariantsDetector:
        h: 0.0001
        maxBaseQS: 30
        minQuality: 40
        maxAlnsPerStartPos: 100
        ignore5: 7
        ignore3: 8
    VCFFilter:
        QC_thresold: 40

GATK:
  interval_length: 1000000