sequencing_units: config/sequencing_units.tsv
sample_units: config/samples.tsv
references: config/references.tsv

resources_config: config/resources.yaml

demultiplexing:
  re_enzyme: "apeKI"

bigtmp: tmpdir/

trimmomatic:
    pe:
      trimmer:
        - "LEADING:5"
        - "TRAILING:5"
        - "SLIDINGWINDOW:4:5"
        - "ILLUMINACLIP:data/adapter.fa:2:20:7:2"
        - "MINLEN:36"

NGSEP:
    path: /home/mnarvaez/software/NGSEPcore/NGSEPcore_5.0.0.jar
    SingleSampleVariantsDetector:
        h: 0.0001
        maxBaseQS: 30
        minQuality: 40
        maxAlnsPerStartPos: 100
        ignore5: 7
        ignore3: 8
    VCFFilter:
        QC_thresold: 40

GATK:
  interval_length: 1000000
  HaplotypeCaller:
    G: ["StandardAnnotation", "StandardHCAnnotation"]
    kmer-size: [11,17,23,29,35,41]
    min_base-qual: 28
    extra:
      - "--do-not-run-physical-phasing"
  CombineGVCFs:
    G: ["StandardAnnotation", "StandardHCAnnotation"]
  GenomicsDBImport:
    genomicsdb-shared-posixfs-optimizations: true
    batch-size: 25
  GenotypeGVCFs:
    interval_length: 1000000
    max-alternate-alleles: 4
    seconds-between-progress-updates: 60
    extra: ["--only-output-calls-starting-in-intervals"]

qualimap:
  path: "/home/mnarvaez/software/qualimap_v2.3/qualimap"

DISCVR-Seq:
  path: "/home/mnarvaez/software/DISCVRSeq/DISCVRSeq-1.3.73.jar"


