# Paths to various input files and configuration settings
sequencing_units: config/sequencing_units.tsv
sample_units: config/samples.tsv
references: config/references.tsv
resources_config: config/resources.yaml

# Settings for the demultiplexing process
demultiplexing:
  re_enzyme: "apeKI"

# Directory for temporary files
bigtmp: tmpdir/

# Trimmomatic settings for paired-end reads
trimmomatic:
    pe:
      trimmer:
        - "LEADING:5"
        - "TRAILING:5"
        - "SLIDINGWINDOW:4:5"
        - "MINLEN:36"
        - "ILLUMINACLIP:data/adapter.fa:2:20:7:2"

# NGSEP software and variant calling settings
NGSEP:
    path: /home/scruz/software/NGSEPcore/NGSEPcore_5.0.0.jar
    SingleSampleVariantsDetector:
        h: 0.0001
        maxBaseQS: 30
        minQuality: 40
        maxAlnsPerStartPos: 100
        ignore5: 7
        ignore3: 8
    VCFFilter:
        QC_thresold: 40

# GATK variant calling settings
GATK:
  interval_length: 1000000
  HaplotypeCaller:
    G: ["StandardAnnotation", "StandardHCAnnotation"]
    kmer-size: [11, 17, 23, 29, 35, 41]
    min_base-qual: 28
    extra:
      - "--do-not-run-physical-phasing"
  CombineGVCFs:
    G: ["StandardAnnotation", "StandardHCAnnotation"]
  GenomicsDBImport:
    genomicsdb-shared-posixfs-optimizations: TRUE
    batch-size: 25
  GenotypeGVCFs:
    interval_length: 1000000
    max-alternate-alleles: 4
    seconds-between-progress-updates: 60
    extra: ["--only-output-calls-starting-in-intervals"]
  SelectVariants:
    select-type-to-include: SNP
    restrict-alleles-to: BIALLELIC
    exclude-filtered: TRUE
